### ISSUE TITLE
CUDA still inactive?

### ISSUE THREAD

**Issue by DevinBayly** [GabrielSCabrera/nBody#2]
Hi there,

I'm playing around with this package on my local supercomputer and even though I have python cupy installed and I register  that python is getting a lift from the gpu
![image](https://user-images.githubusercontent.com/11687631/105927009-50fdaa00-6000-11eb-945a-ab0e70eaac3c.png)
it still says `CUDA inactive`

![image](https://user-images.githubusercontent.com/11687631/105927061-725e9600-6000-11eb-9973-27f91a658a43.png)

Any ideas why this is? Am I getting all the speedups you expect for the simple orbits code?

**Comment by DevinBayly** [comment]
I'll close this as it looks like `S.solve(T,dt,collision=True,GPU=True)` did the trick, but there seems to be a cuda error.

**Comment by GabrielSCabrera** [comment]
Thanks for getting in contact with me about nBody!  

As you may have now noticed, there are actually 3 CPU/GPU modes.  The user can select GPU=True or GPU=False if they wish to explicitly use the GPU or CPU, respectively, but if they leave the argument blank then a few test iterations are run on both the CPU and GPU.  These are then timed, compared, and the fastest is automatically selected.  This is to take advantage of JIT for smaller simulations, which in my personal experience seem to run slower on the GPU (perhaps due to overhead?)

If this is not functioning properly however, let me know and I will take a deep dive and see if I can identify the issue!

**Comment by GabrielSCabrera** [comment]
I see now you mention a CUDA error, I will try and identify why this is happening and upload a fix

**Comment by DevinBayly** [comment]
Good to hear from you! I'm loving the simplicity and straightforwardness of
this package and it'll be great when all the capabilities are running
smoothly.

Ill post the error message when i get in front of my machine next time but
its related to mixing numpy and cupy types.
